Emotion Recognition

Dataset : From hugging face library


In [1]:
!pip install accelerate
!pip install transformers
!pip install datasets


     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 302.4/302.4 kB 2.5 MB/s eta 0:00:00
  Using cached nvidia_cuda_nvrtc_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (23.7 MB)
  Using cached nvidia_cuda_runtime_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (823 kB)
  Using cached nvidia_cuda_cupti_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (14.1 MB)
  Using cached nvidia_cudnn_cu12-8.9.2.26-py3-none-manylinux1_x86_64.whl (731.7 MB)
  Using cached nvidia_cublas_cu12-12.1.3.1-py3-none-manylinux1_x86_64.whl (410.6 MB)
  Using cached nvidia_cufft_cu12-11.0.2.54-py3-none-manylinux1_x86_64.whl (121.6 MB)
  Using cached nvidia_curand_cu12-10.3.2.106-py3-none-manylinux1_x86_64.whl (56.5 MB)
  Using cached nvidia_cusolver_cu12-11.4.5.107-py3-none-manylinux1_x86_64.whl (124.2 MB)
  Using cached nvidia_cusparse_cu12-12.1.0.106-py3-none-manylinux1_x86_64.whl (196.0 MB)
  Using cached nvidia_nccl_cu12-2.19.3-py3-none-manylinux1_x86_64.whl (166.0 MB)
  Using cached nvidia_nvtx_cu12-12.1.105-py3-none-many

In [2]:
from datasets import load_dataset, list_datasets
import pandas as pd

In [3]:
all_dataset = list_datasets()

<ipython-input-3-2fb2b241c4a0>:1: FutureWarning: list_datasets is deprecated and will be removed in the next major version of datasets. Use 'huggingface_hub.list_datasets' instead.
  all_dataset = list_datasets()
/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_token.py:89: UserWarning: 
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(


In [4]:
"dair-ai/emotion" in all_dataset

True

In [5]:
# loading the dataset
emotion = load_dataset("emotion")
emotion.set_format(type = 'pandas')

/usr/local/lib/python3.10/dist-packages/datasets/load.py:1486: FutureWarning: The repository for emotion contains custom code which must be executed to correctly load the dataset. You can inspect the repository content at https://hf.co/datasets/emotion
You can avoid this message in future by passing the argument `trust_remote_code=True`.
Passing `trust_remote_code=True` will be mandatory to load this dataset from the next major release of `datasets`.
  warnings.warn(


Generating train split:   0%|          | 0/16000 [00:00<?, ? examples/s]

Generating validation split:   0%|          | 0/2000 [00:00<?, ? examples/s]

Generating test split:   0%|          | 0/2000 [00:00<?, ? examples/s]

In [6]:
emotion

DatasetDict({
    train: Dataset({
        features: ['text', 'label'],
        num_rows: 16000
    })
    validation: Dataset({
        features: ['text', 'label'],
        num_rows: 2000
    })
    test: Dataset({
        features: ['text', 'label'],
        num_rows: 2000
    })
})

In [7]:
type(emotion)

datasets.dataset_dict.DatasetDict

In [8]:
train_df = emotion["train"][:]

In [9]:
train_df.head()

text  label
0                            i didnt feel humiliated      0
1  i can go from feeling so hopeless to so damned...      0
2   im grabbing a minute to post i feel greedy wrong      3
3  i am ever feeling nostalgic about the fireplac...      2
4                               i am feeling grouchy      3

In [10]:
classes = train_df["label"].unique()
classes

array([0, 3, 2, 5, 4, 1])

In [43]:
label_class = emotion['train'].features['label'].names
label_class

['sadness', 'joy', 'love', 'anger', 'fear', 'surprise']

In [12]:
emotion['train'].features["label"]

ClassLabel(names=['sadness', 'joy', 'love', 'anger', 'fear', 'surprise'], id=None)

### Tokenizing

In [13]:
# importing libraries
from transformers import AutoTokenizer
model_ckpt = "distilbert-base-uncased"
tokenizer = AutoTokenizer.from_pretrained(model_ckpt)

/usr/local/lib/python3.10/dist-packages/huggingface_hub/file_download.py:1132: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(


tokenizer_config.json:   0%|          | 0.00/28.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/483 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

In [33]:
text = "I love Machine Learning!. Tokenization is awesome"
encoded_text = tokenizer(text)
print(encoded_text)

{'input_ids': [101, 1045, 2293, 3698, 4083, 999, 1012, 19204, 3989, 2003, 12476, 102], 'attention_mask': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]}


In [38]:
type(encoded_text)

transformers.tokenization_utils_base.BatchEncoding

In [42]:
tokens = tokenizer.convert_ids_to_tokens(encoded_text.input_ids)
print(tokens)

['[CLS]', 'i', 'love', 'machine', 'learning', '!', '.', 'token', '##ization', 'is', 'awesome', '[SEP]']


In [43]:
t = "i said it was good"
encod_t = tokenizer(t)
print(encod_t)

{'input_ids': [101, 1045, 2056, 2009, 2001, 2204, 102], 'attention_mask': [1, 1, 1, 1, 1, 1, 1]}


### Tokenizing emotion data

In [14]:
emotion.reset_format()

In [15]:
# function to tokenize
def tokenize(batch):
  temp = tokenizer(batch["text"], padding = True, truncation = True)
  return temp

In [16]:
emotions_encoded = emotion.map(tokenize, batched=True, batch_size=None)

Map:   0%|          | 0/16000 [00:00<?, ? examples/s]

Asking to truncate to max_length but no maximum length is provided and the model has no predefined maximum length. Default to no truncation.


Map:   0%|          | 0/2000 [00:00<?, ? examples/s]

Map:   0%|          | 0/2000 [00:00<?, ? examples/s]

In [17]:
emotions_encoded

DatasetDict({
    train: Dataset({
        features: ['text', 'label', 'input_ids', 'attention_mask'],
        num_rows: 16000
    })
    validation: Dataset({
        features: ['text', 'label', 'input_ids', 'attention_mask'],
        num_rows: 2000
    })
    test: Dataset({
        features: ['text', 'label', 'input_ids', 'attention_mask'],
        num_rows: 2000
    })
})

## Model Building

In [18]:
from transformers import AutoModel
import torch

model = AutoModel.from_pretrained(model_ckpt)

/usr/local/lib/python3.10/dist-packages/huggingface_hub/file_download.py:1132: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(


model.safetensors:   0%|          | 0.00/268M [00:00<?, ?B/s]

## Fine tuning

In [19]:
from transformers import AutoModelForSequenceClassification

num_labels = len(classes)
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

model = AutoModelForSequenceClassification.from_pretrained(model_ckpt, num_labels = num_labels).to(device)


Some weights of DistilBertForSequenceClassification were not initialized from the model checkpoint at distilbert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight', 'pre_classifier.bias', 'pre_classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


In [20]:
device

device(type='cuda')

In [21]:
from transformers import TrainingArguments

In [22]:
batch_size = 16
model_name = "distilbert-finetuned-emotion"

training_args = TrainingArguments(output_dir = "outputs/" + model_name,
                                  num_train_epochs = 10,
                                  learning_rate = 2e-5,
                                  per_device_train_batch_size = batch_size,
                                  per_device_eval_batch_size = batch_size,
                                  weight_decay= 0.01,
                                  evaluation_strategy = 'epoch',
                                  disable_tqdm = False)

In [23]:
from sklearn.metrics import accuracy_score, f1_score

def compute_metrics(pred):
  labels = pred.label_ids
  preds = pred.predictions.argmax(-1)
  f1 = f1_score(labels, preds, average='weighted')
  acc = accuracy_score(labels, preds)
  return {"accuracy": acc, "f1": f1}

In [24]:
from transformers import Trainer


trainer = Trainer(model=model, args=training_args,
                  compute_metrics=compute_metrics,
                  train_dataset=emotions_encoded['train'],
                  eval_dataset=emotions_encoded['validation'],
                  tokenizer=tokenizer)

In [25]:
trainer.train()

TrainOutput(global_step=10000, training_loss=0.10500756998062134, metrics={'train_runtime': 1511.5458, 'train_samples_per_second': 105.852, 'train_steps_per_second': 6.616, 'total_flos': 3601714308480000.0, 'train_loss': 0.10500756998062134, 'epoch': 10.0})

In [28]:
model_path = "/content/drive/MyDrive/llm_trainings/models/" + "emotion_recognition.h5"

In [29]:
trainer.save_model(model_path)

In [30]:
preds_outputs = trainer.predict(emotions_encoded['test'])
preds_outputs.metrics

{'test_loss': 0.42787858843803406,
 'test_accuracy': 0.924,
 'test_f1': 0.9238952635051765,
 'test_runtime': 6.3173,
 'test_samples_per_second': 316.59,
 'test_steps_per_second': 19.787}

In [31]:

import numpy as np
y_preds = np.argmax(preds_outputs.predictions, axis=1)
y_true = emotions_encoded['test'][:]['label']

In [36]:

from sklearn.metrics import classification_report
print(classes)
print(classification_report(y_true, y_preds))

[0 3 2 5 4 1]
              precision    recall  f1-score   support

           0       0.96      0.98      0.97       581
           1       0.94      0.94      0.94       695
           2       0.80      0.79      0.79       159
           3       0.94      0.91      0.93       275
           4       0.88      0.92      0.90       224
           5       0.75      0.73      0.74        66

    accuracy                           0.92      2000
   macro avg       0.88      0.88      0.88      2000
weighted avg       0.92      0.92      0.92      2000



In [44]:
text = 'i am happy to say that things.'
input_encoded = tokenizer(text, return_tensors='pt').to(device)
with torch.no_grad():
  outputs = model(**input_encoded)

logits = outputs.logits
pred = torch.argmax(logits, dim=1).item()
pred, label_class[pred]


(1, 'joy')

In [38]:
outputs

SequenceClassifierOutput(loss=None, logits=tensor([[-2.4838,  8.8277, -2.2933, -2.6639, -3.8899, -3.7229]],
       device='cuda:0'), hidden_states=None, attentions=None)

In [39]:
logits

tensor([[-2.4838,  8.8277, -2.2933, -2.6639, -3.8899, -3.7229]],
       device='cuda:0')

In [40]:
torch.argmax(logits, dim =1)

tensor([1], device='cuda:0')