## Text Classification

In [4]:
import json

In [5]:
def load_json(file_path):
  with open(file_path, "r") as fp:
    data = json.load(fp)

  return data

In [ ]:
train_data = load_json("train_data.json")
test_data = load_json("test_data.json")
val_data = load_json("val_data.json")

In [ ]:
train_data.keys()

dict_keys(['input_ids', 'token_type_ids', 'attention_mask', 'labels'])

In [ ]:
test_data.keys()

dict_keys(['input_ids', 'token_type_ids', 'attention_mask', 'labels'])

In [ ]:
val_data.keys()

dict_keys(['input_ids', 'token_type_ids', 'attention_mask', 'labels'])

## Create Dataset format

In [3]:
!pip install datasets

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 542.1/542.1 kB 2.8 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 116.3/116.3 kB 10.1 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 64.9/64.9 kB 3.7 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 194.1/194.1 kB 15.8 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 134.8/134.8 kB 13.6 MB/s eta 0:00:00
  Attempting uninstall: requests
    Found existing installation: requests 2.31.0
    Uninstalling requests-2.31.0:
      Successfully uninstalled requests-2.31.0
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
google-colab 1.0.0 requires requests==2.31.0, but you have requests 2.32.3 which is incompatible.


In [ ]:
from datasets import Dataset

In [ ]:
train_dataset = Dataset.from_dict(train_data)
test_dataset = Dataset.from_dict(test_data)
val_dataset = Dataset.from_dict(val_data)

In [ ]:
train_dataset

Dataset({
    features: ['input_ids', 'token_type_ids', 'attention_mask', 'labels'],
    num_rows: 50
})

In [ ]:
test_dataset

Dataset({
    features: ['input_ids', 'token_type_ids', 'attention_mask', 'labels'],
    num_rows: 20
})

In [ ]:
val_dataset

Dataset({
    features: ['input_ids', 'token_type_ids', 'attention_mask', 'labels'],
    num_rows: 30
})

## Training it with transformers

In [5]:
!pip install -U accelerate
!pip install -U transformers

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 302.6/302.6 kB 2.1 MB/s eta 0:00:00
  Using cached nvidia_cuda_nvrtc_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (23.7 MB)
  Using cached nvidia_cuda_runtime_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (823 kB)
  Using cached nvidia_cuda_cupti_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (14.1 MB)
  Using cached nvidia_cudnn_cu12-8.9.2.26-py3-none-manylinux1_x86_64.whl (731.7 MB)
  Using cached nvidia_cublas_cu12-12.1.3.1-py3-none-manylinux1_x86_64.whl (410.6 MB)
  Using cached nvidia_cufft_cu12-11.0.2.54-py3-none-manylinux1_x86_64.whl (121.6 MB)
  Using cached nvidia_curand_cu12-10.3.2.106-py3-none-manylinux1_x86_64.whl (56.5 MB)
  Using cached nvidia_cusolver_cu12-11.4.5.107-py3-none-manylinux1_x86_64.whl (124.2 MB)
  Using cached nvidia_cusparse_cu12-12.1.0.106-py3-none-manylinux1_x86_64.whl (196.0 MB)
  Using cached nvidia_nccl_cu12-2.20.5-py3-none-manylinux2014_x86_64.whl (176.2 MB)
  Using cached nvidia_nvtx_cu12-12.1.105-py3-none-m

### Saving Tokenizer

In [ ]:
tokenizer = AutoTokenizer.from_pretrained("bert-base-uncased")

/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_token.py:89: UserWarning: 
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(


tokenizer_config.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

/usr/local/lib/python3.10/dist-packages/huggingface_hub/file_download.py:1132: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(


config.json:   0%|          | 0.00/570 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

In [ ]:
import os
tokenizer_path = os.path.join("/content/drive/MyDrive/llm_trainings/models", "news_classifier_tokenizer")

In [ ]:
tokenizer.save_pretrained(tokenizer_path)

('/content/drive/MyDrive/llm_trainings/models/news_classifier_tokenizer/tokenizer_config.json',
 '/content/drive/MyDrive/llm_trainings/models/news_classifier_tokenizer/special_tokens_map.json',
 '/content/drive/MyDrive/llm_trainings/models/news_classifier_tokenizer/vocab.txt',
 '/content/drive/MyDrive/llm_trainings/models/news_classifier_tokenizer/added_tokens.json',
 '/content/drive/MyDrive/llm_trainings/models/news_classifier_tokenizer/tokenizer.json')

In [ ]:
from sklearn.metrics import accuracy_score, precision_recall_fscore_support

In [ ]:
from transformers import AutoTokenizer,AutoModelForSequenceClassification, TrainingArguments, Trainer

In [ ]:
def compute_metrics(pred):

        labels = pred.label_ids

        preds = pred.predictions.argmax(-1)

        precision, recall, f1, _ = precision_recall_fscore_support(labels, preds, average='macro')

        acc = accuracy_score(labels, preds)

        # Return the computed metrics as a dictionary
        return {
            'Accuracy': acc,
            'F1': f1,
            'Precision': precision,
            'Recall': recall
        }

In [ ]:
import os
model_output_dir = os.path.join("/content/drive/MyDrive/llm_trainings/models", "news_classifier")

In [ ]:
training_args = TrainingArguments(
            output_dir = "./outputs",
            num_train_epochs = 10,
            per_device_train_batch_size= 4,
            per_device_eval_batch_size=4,
            learning_rate = 2e-5,
            disable_tqdm = False
        )

In [ ]:
import torch
device = "cuda" if torch.cuda.is_available() else "cpu"

In [ ]:
device

'cuda'

In [ ]:
model = AutoModelForSequenceClassification.from_pretrained("bert-base-uncased", num_labels = 5, device_map = device)

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at bert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


In [ ]:
trainer = Trainer(
    model = model,
    args = training_args,
    train_dataset = train_dataset,
    eval_dataset = val_dataset,
    compute_metrics = compute_metrics
)

In [ ]:
training_result = trainer.train()

In [ ]:
training_result

TrainOutput(global_step=130, training_loss=1.618264887883113, metrics={'train_runtime': 52.9115, 'train_samples_per_second': 9.45, 'train_steps_per_second': 2.457, 'total_flos': 131559071232000.0, 'train_loss': 1.618264887883113, 'epoch': 10.0})

In [ ]:
type(training_result)

transformers.trainer_utils.TrainOutput

In [ ]:
import os
save_model_path = os.path.join("/content/drive/MyDrive/llm_trainings/models", "news_classifier_model")

In [ ]:
trainer.save_model(save_model_path)

In [ ]:
trainer.label_names

['labels']

In [ ]:
trainer.save_metrics

<bound method save_metrics of <transformers.trainer.Trainer object at 0x7fdef9733280>>

## Load pretrained model

In [1]:
from transformers import AutoTokenizer, AutoModelForSequenceClassification

In [2]:
import os
pretrained_model_path = os.path.join("/content/drive/MyDrive/llm_trainings/models", "news_classifier_model")


In [3]:
tokenizer_path = os.path.join("/content/drive/MyDrive/llm_trainings/models", "news_classifier_tokenizer")

In [4]:
pretrained_tokenizer = AutoTokenizer.from_pretrained(tokenizer_path)

In [5]:
pretrained_model = AutoModelForSequenceClassification.from_pretrained(pretrained_model_path)

In [34]:
input_text = "tv future in the hands of viewers with home theatre systems  plasma high-definition tvs  and digital video recorders moving into the living room"

In [35]:
tokenized_text = pretrained_tokenizer(input_text,
                             truncation=True,
                             is_split_into_words=False,
                             return_tensors='pt')

In [36]:
tokenized_text.keys

<bound method BatchEncoding.keys of {'input_ids': tensor([[  101,  2694,  2925,  1999,  1996,  2398,  1997,  7193,  2007,  2188,
          3004,  3001, 12123,  2152,  1011,  6210,  2694,  2015,  1998,  3617,
          2678, 14520,  2015,  3048,  2046,  1996,  2542,  2282,   102]]), 'token_type_ids': tensor([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0]]), 'attention_mask': tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1]])}>

In [37]:
tokenized_text["input_ids"]

tensor([[  101,  2694,  2925,  1999,  1996,  2398,  1997,  7193,  2007,  2188,
          3004,  3001, 12123,  2152,  1011,  6210,  2694,  2015,  1998,  3617,
          2678, 14520,  2015,  3048,  2046,  1996,  2542,  2282,   102]])

In [38]:
type(tokenized_text["input_ids"])

torch.Tensor

In [40]:
tokenized_text["input_ids"].shape

torch.Size([1, 29])

In [10]:
outputs = pretrained_model(tokenized_text["input_ids"])

In [11]:
outputs.logits.argmax(-1)

tensor([2])

In [12]:
predicted_label = outputs.logits.argmax(-1)
predicted_label

tensor([2])

In [23]:
pretrained_model.num_labels

5

## Testing Data

In [8]:
import json
def load_json(file_path):
  with open(file_path, "r") as fp:
    data = json.load(fp)

  return data

In [9]:
test_data = load_json("train_data.json")

In [10]:
test_data.keys()

dict_keys(['input_ids', 'token_type_ids', 'attention_mask', 'labels'])

In [26]:
import torch
def get_prediction(input_ids):
  predicted_labels = []
  for i in range(len(input_ids)):
    print(f"Predicting input {i} ---> {len(input_ids)} ")
    predicted_input = torch.tensor([input_ids[i]])
    preds = pretrained_model(predicted_input)

    predicted_labels.append(preds.logits.argmax())

  return predicted_labels

In [28]:
predicted_labels = get_prediction(test_data["input_ids"][:20])

Predicting input 0 ---> 20 
Predicting input 1 ---> 20 
Predicting input 2 ---> 20 
Predicting input 3 ---> 20 
Predicting input 4 ---> 20 
Predicting input 5 ---> 20 
Predicting input 6 ---> 20 
Predicting input 7 ---> 20 
Predicting input 8 ---> 20 
Predicting input 9 ---> 20 
Predicting input 10 ---> 20 
Predicting input 11 ---> 20 
Predicting input 12 ---> 20 
Predicting input 13 ---> 20 
Predicting input 14 ---> 20 
Predicting input 15 ---> 20 
Predicting input 16 ---> 20 
Predicting input 17 ---> 20 
Predicting input 18 ---> 20 
Predicting input 19 ---> 20 


In [30]:
print(predicted_labels)

[tensor(3), tensor(3), tensor(4), tensor(3), tensor(3), tensor(3), tensor(3), tensor(3), tensor(3), tensor(1), tensor(3), tensor(3), tensor(3), tensor(4), tensor(3), tensor(3), tensor(3), tensor(3), tensor(3), tensor(3)]


In [31]:
actual_labels = test_data["labels"][:20]

In [32]:
print(actual_labels)

[4, 0, 3, 3, 1, 2, 2, 3, 3, 1, 1, 0, 0, 2, 3, 0, 2, 3, 0, 4]


## Checking report

In [35]:
from sklearn.metrics import confusion_matrix, accuracy_score, precision_recall_fscore_support

In [36]:
precision, recall, f1, _ = precision_recall_fscore_support(actual_labels, predicted_labels, average='macro')

acc = accuracy_score(actual_labels, predicted_labels)



/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [37]:
report = {
            'Accuracy': acc,
            'F1': f1,
            'Precision': precision,
            'Recall': recall
        }

In [38]:
print(report)

{'Accuracy': 0.3, 'F1': 0.18695652173913044, 'Precision': 0.25882352941176473, 'Recall': 0.23333333333333334}


In [40]:
c_met

array([[0, 0, 0, 5, 0],
       [0, 1, 0, 2, 0],
       [0, 0, 0, 3, 1],
       [0, 0, 0, 5, 1],
       [0, 0, 0, 2, 0]])